
name: CI

on:
  push:
    paths:
      - '**.go'
      - 'Dockerfile'
      - 'go.*'
      - 'templates/**'
      - 'pdf/**'
      - 'musescore/**'
      - '.github**/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Upload docker image
        run: |
          IMAGE=$GITHUB_REPOSITORY
          TAG=$GITHUB_SHA-$GITHUB_RUN_ID
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG
          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:latest
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          docker tag $IMAGE:$TAG $IMAGE:$BRANCH
          docker push $IMAGE:$BRANCH
#  generate-docs:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: recursive
#      - uses: azure/docker-login@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_SECRET }}
#      - uses:
#          docker run -v $(pwd):/workdir -w /workdir piotrpersona/sheetmusic:latest
